DROP TABLE IF EXISTS marks;

CREATE TABLE marks (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    geometry TEXT NOT NULL,
    properties TEXT NOT NULL
);